server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native #配置文件的获取方式 native表示从本地去拿
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared