server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    filter-only-up-instances: true
feign:
  hystrix:
    enabled: true  #是否开启熔断器


